image: debian:stable

pages:
  script:
    - apt update && apt -y install texlive-full pandoc make
    - make -B
    - mkdir -p public
    - cp out.pdf out.html public
  artifacts:
    paths:
      - public
