image: debian:stable

build:
  stage: build
  before_script:
    - apt update && apt -y install texlive-full pandoc make
  script:
    - make -B
  artifacts:
    paths:
      - out.pdf
      - out.html
