# Appendices {.unlisted .unnumbered}

## More on Housing {#sec:morehousing}

The Institute has undergone significant expansion and increase in number of students over the last decade and a half. The increase in student numbers has led to a commensurate increase in the number of faculty members on the campus. Thus, the present dwelling numbers on the campus are insufficient. Though, new constructions are underway, there is an expected shortage of housing on campus for some more time. In most cases, the new faculty may take up on-campus housing flatlets like the Staff Hostel, Vihar House and CSRE D Types. However, some faculty may want a "proper apartment" owing to family constraints or due to non-availability of the flatlets. In such situations, some may opt for off-campus housing. These off-campus housing once identified and allotted are treated as an extension of the IIT Bombay housing. There are several considerations to be made when scouting for an apartment. Below are a few points to be considered with regard to off-campus housing.

The Institute provides temporary accommodation in the Guest House to the new faculty member immediately after they join, up to a period of 1 month. The guest house charges are applicable and have to be borne by the faculty if this initial period of 30 days is exceeded. It is thus recommended that a search for off-campus housing be initiated as soon as the joining formalities are completed.

An off-campus rented apartment requires consideration of the amount of rent, brokerage, escalation clause and issues related to maintenance and movement charges. The Institute has evolved a policy on the amount of rent that can be paid. The decisions regarding the amount of rent, brokerage and escalation clause are usually handled by the Associate Dean IPS-2 and his/her Office. As a first step, new faculty members  are advised to contact the office of Associate Dean-2 Infrastructure and Planning (IPS) to obtain information on the rental limits and other rules regarding off-campus accommodation. It is recommended that the initial negotiated rent is limited to within the stipulated amount. The terms and issues regarding the escalation are handled by the Associate Dean IPS-2's office. The maintenance and movement charges are usually expected to be borne by the faculty.

The Associate Dean IPS-2's office may also offer help for searching and to identify estate agents who can facilitate the search for apartments. A list of previously rented apartments or apartments newly offered on rent may be already be available with the Office of the Associate Dean IPS-2. These may be considered by new faculty for potential allotment. The identification of the apartment could also be done personally with the help of an agent, or by consulting websites that offer such solutions.

The contract or the lease agreement is drawn with IIT Bombay as the party and the letter of allotment is then issued by the Accommodation Allotment Committee (AAC). The duration of the lease should be checked carefully, since, it may be possible that these rented premises may have to occupied for an extended period of time. After moving to the apartment, the usual day to day maintenance is expected to be handled by the allottee.

The Institute has rules and regulations regarding allotment and entitlement of housing to faculty and staff of the Institute. The details of these can be found on the Dean IPS website. The off-campus housing is treated as transit accommodation provided by IIT Bombay. Thus, availing the off-campus housing does not affect the entitlement or the seniority of the faculty within the ambit of the defined rules. The rented premises may have to vacated due to several reasons with the happy one being on-campus accommodation.

### Staff Hostel

The Staff Hostel at IIT Bombay provides temporary accommodation for
new faculty members opting to stay on campus. This housing includes up
to 1 BHK units and is allocated based on availability, serving as a
transitional solution until permanent housing is secured. For more
details on housing policies, please refer to the relevant section on
housing in the Faculty Handbook.

### Staff Hostel Mess

The mess within the Staff Hostel offers faculty members simple,
home-style meals at affordable prices. Open to both hostel residents
and other faculty members, the mess serves as a welcoming space where
meals become more than just a routine activity. It's a place where new
faculty can take a break from their busy schedules and engage in
meaningful conversations with colleagues. Sharing a meal here often
leads to building connections with other faculty members, exchanging
ideas, and even forming friendships.

In particular, the mess provides a unique opportunity for new faculty
to seek advice and guidance from more experienced colleagues in an
informal setting. This environment fosters a sense of community and
belonging, which can be incredibly supportive during the early stages
of your journey at IIT Bombay. Many faculty members have found the
interactions in the mess to be invaluable for networking, gaining
insights, and feeling more integrated into the campus community.


## Schools in and around campus {#sec:moreschools}

### PM Shri Kendriya Vidyalaya (Central School) IIT Powai
This is part of the PM Shri Kendriya Vidyalaya Sangathan (KVS) network and is usually ranked among the top government day (that is,  not boarding) schools in India. It has classes I through XII and is affiliated to the Central Board of Secondary Education (CBSE). More details about KV IIT Bombay may be found on [its webpage](https://iitpowai.kvs.ac.in/).


### Campus School and Jr. College
The IIT Campus School and Jr. College has classes I through XII and is affiliated to the Maharashtra State Board. It is exclusively for the children of IIT employees. Here, the IIT Bombay Director is the Chairperson of the School Council and IIT faculty serve as Associate Chairperson and Conveners of Administrative and Academic policy. More details about the Campus School are available [here](https://www.iitbcampusschool.ac.in/).

### KG School
The Kindergarten (KG) School comprising two classes (Lower KG and Upper KG) and two shifts, is for children from three to five years of age. Details of admissions, facilities, etc. that the KG School offers may be found [here](http://home.iitb.ac.in/~kgschool/index.html).

### Schools outside campus
There are also several private schools in the Powai area, including
Podar International School, Bombay Scottish Scool, Gopal Sharma
International School, and more. Many of these school's buses ply
within campus so that the travel is convenient for the children.

### Shishu Vihar Child Care Centre

Shishu Vihar is a not-for-profit child care centre, managed by an
association of parents, catering primarily to the child care needs of
working parents in IIT Bombay. The Shishu Vihar Management Committee
(SVMC) is a body of IIT Bombay Official Representatives and elected member
parents. SVMC is responsible for the overall policy, human resources,
and financial management of the centre.

SV has a group of people with backgrounds in education, psychology,
special needs, child development, early childhood education and
curriculum development. Their education and experience not only
enables them to understand the needs of children, but also inspires
them to choose healthy and effective practices in child care.

Shishu Vihar, which is located near Main Gate, has the following time slots and programs.

Slots                                    Hours      Timing
---------------------------------------  ---------  ------------------
Morning Slot (MS)                        5 hours    8:15 AM to 1:15 PM
Afternoon Slot (AF)                      5 hours    1:15 PM to 6:15 PM
3/4 Day Slot (Lower KG School Children)  7.5 hours  Flexible
Full Day Slot (FD)                       10 hours   8:15 AM to 6:15 PM

------------------------------------------------------------------------------------
Programs              Eligibility             Description
--------------------  ---------------------   --------------------------------------
Toddler Program (MS)  18 months               A planned program where
                                              toddlers are stimulated
                                              through music, rhymes, books and toys.

Play Group (MS)       2 years                 A structured program
                                              that focuses on Sensory,
                                              Language and
											  Social Development. Children
                                              are motivated to learn
                                              and explore through
											  play.

Junior Club (MS)      3 years                 A systematic program
                                              that uses reasoning,
                                              math and language skills
                                              to facilitate thematic
                                              learning among children.

Day Care (FD/AS)      18 months to 12 years   Children are exposed to
                                              various activities such
                                              as art & craft, music,
                                              storytelling etc. Indoor
                                              and outdoor play is
                                              strongly encouraged.
------------------------------------------------------------------------------------

Some more details about Shishu Vihar may be found [here](https://www.facebook.com/pg/Sishu-Vihar-441328895915841/about/).