# Continuing and Executive Education Programmes {#sec:cep}

The office of Educational Outreach (EO) offers courses and programmes
in outreach mode, that are aimed at outsiders who are not enrolled to
any in-campus academic degree programme. These courses (and
degree/diploma programmes) are aimed at (i) skilling, up-skilling and
re-skilling of working professionals through CEP and PCACEC, (ii)
education of university/college students through platforms like NPTEL,
SWAYAM, Swayam Prabha and IITB's official EdTech Service Providers,
and (iii) research and education needs of college teachers through
various Government missions, such as QIP and MERITE.

All such "extra-Academic" courses and programmes have been created by
the IIT Bombay faculty, with the help of the EO office. Please check
the [EO website](https://www.cep.iitb.ac.in/) to have an understanding
of the variety of offerings including their delivery modes, target
audience, hosting mechanism, etc. Offering EO courses can add
significantly to your earnings. If you are interested in creating and
offering EO courses, please check the EO Handbook or drop an email to
[dean.eo.office@iitb.ac.in](mailto:dean.eo.office@iitb.ac.in) for
discussion. The EO office will provide the necessary infrastructural
and logistical support.