---
description: "Ethics and code of conduct for IIT Bombay faculty — academic integrity, conflict of interest, misconduct procedures, and professional standards."
keywords: "IITB ethics, IIT Bombay code of conduct, academic integrity, conflict of interest, faculty misconduct"
---

# Ethics and Code of Conduct
As a faculty member of a premier Institute of the country, you are always under public scrutiny. It is necessary to maintain a high degree of decorum and integrity at all times. Clearly, it is not possible to give a complete list of what is acceptable and what is not. This section, therefore, deals only with such items as we believe you should be well informed about.

## Matters of general conduct

1. _Dealing with the Press:_ Much as we like to see our name in print, the only place where your printed name can freely appear without raising eyebrows (or may be raising eyebrows in an agreeable way!) is in a professional journal. You do not need to take any permission to send a technical manuscript for publication. If what you are writing or talking about is of literary, artistic or scientific value only, you may even write to newspapers or periodicals. However, talking to the press (this includes all forms of interaction with print and electronic media) on any other matter  should generally be avoided, and left to functionaries in the Main Building. If you would like to express your views on an issue, you need to take the Director's permission. If you want to have a press coverage of your published scientific article, you need to contact PRO after taking permission from the Director.
2. Joining a political party or canvassing in an election is banned. (You can, of course, contest an election in a professional body.)
3. Criticism of the Institute in any mass media (print or electronic)
   is not permitted. This
   [circular](https://bighome.iitb.ac.in/index.php/s/LDFrcxW7Bdoa6wZ)
   details this aspect in connection to the service rules. (To give
   vent to your frustration if any, the Computer Centre of the
   Institute has provided a discussion group called the
   'discuss-faculty' where you can write and engage your colleagues in
   a debate on matters about which you feel strongly. This newsgroup
   is not moderated but it is good to use restrained language).
3. _Redressal of Grievances:_: If you have a grievance, try to sort it out by meeting the concerned Dean, the Deputy Directors or the Director. If you would like to make a written representation, the first course is the Director. If his response leaves you dissatisfied, you may make representation to the Chairperson of the Board. Such representation should go through, Head, concerned Dean,
Director and the Chairperson in that order. In extreme cases, you may take your grievance to the Visitor (who is the President of India). However, in all cases, you should go through what is known as proper channel, that is, route all your representation through HOD, Director and the Chairperson, in that order. The forwarding authority does not have the right to stop your representation being forwarded upwards excepting in circumstances such as (i) a similar petition made earlier has been disposed of and no new facts are brought out in the new petition, (ii) your representation is not to the appropriate authority, or (iii) the petition is against a decision which is final by any law or statute. In such cases, the appropriate authority will write you a reply explaining the reasons why your petition may not be forwarded.
4. You may, of course, seek to redress grievances in a court of law without any permission. However, it is in good taste to first exhaust all possibilities of finding a solution to  your problems within the internal framework as stated above.
5. _Social media usage policy_: Social media posts from IIT Bombay connected official accounts are governed by rules specified in [this document](https://www.iitb.ac.in/sites/www.iitb.ac.in/files/Guidelines%20For%20Use%20Of%20Offical%20IIT%20Bombay%20Accounts%20On%20Social%20Media_2.pdf).

::: {.review}
## Periodic review under FR 56(J)/(I)

The Board of Governors, in its 271st meeting on 6 December 2024,
adopted the provisions of FR 56(J)/(I) and Rule 42 of the CCS (Pension)
Rules, 2021. Institute employees are periodically reviewed on the
following parameters: doubtful integrity, ineffectiveness, and conduct
unbecoming of a Government servant. Heads of Departments/Sections
periodically review employees on these parameters and forward any such
cases to the concerned authority.

:::

## Sexual Harassment and Gender Cell

As a teacher you would interact with a lot of students, who would be
male, female or those of gender and sexual minorities. Likewise, you would
interact with colleagues and other staff belonging to different
sexes. In many cases, you would have a supervisory role in the
interaction. Your behaviour in all such interactions must be
impeccable. Please remember that they have a right to a place of work
or study where they do not face sexual harassment in any form - and
you have a responsibility to provide it. You are also responsible for
the conduct of the staff and students who are working in your
supervision and ensuring that they do not indulge in any acts of
sexual harassment. The Sexual Harassment of Women at Workplace
(Prevention, Prohibition and Redressal) Act, 2013 defines sexual
harassment as unwelcome sexual behaviour, whether directly or by
implication, such as through:

- physical contact and advances
- demand or request for sexual favours
- sexually colored remarks (this includes colored jokes in a mixed
company, or a class room, or even within hearing distance of the complainant)
- showing pornography
- any other unwelcome physical, verbal or non-verbal conduct of sexual nature.

A more comprehensive definition of sexual harassment can be found in
the IITB policy on sexual harassment
[here](https://www.gendercell.iitb.ac.in/policy.pdf).


A victim of sexual harassment (or one who perceives sexual harassment
to oneself) may lodge a complaint to the Gender Cell Internal
Complaints Committee (GC-ICC), the Director, Deputy Director or to the
Dean (FA), in addition to seeking redress under the Indian Penal
Code. Students can also take their complaint to the Dean (SA).

Any woman can approach the Gender Cell for complaints against a member
of the Institute (employee or student) regarding workplace related
harassment. In addition, the Gender Cell can also be approached by a
male student or a student belonging to sexual minorities for
complaints against a male student or employee, when the sexual
harassment is alleged to have taken place within the campus or the
workplace. The Gender Cell inquires into sexual harassment complaints
through its ICC. An inquiry by the ICC has the status of an official
inquiry under the Civil Service Rules, and employees have to cooperate
with the Cell in its investigations. In addition, sexual harassment is
an offence under rule 3C of the Central Civil Services (Conduct)
Rules. More details about the Gender Cell may be found
[here](http://www.gendercell.iitb.ac.in/); links to the IIT Bombay
policy document, the Sexual Harassment at the Workplace Act, and a
government handbook on sexual harassment, are given
[here](https://www.gendercell.iitb.ac.in/icc.html).

The Gender Cell at IIT Bombay has developed an online training on
gender issues, sexual harassment and role of consent in the work
place. The course also gives an overview of the process at IIT Bombay
to address sexual harassment. Every faculty is required to do this
training at the earliest. It is available on the [internal
Moodle](https://xmoodle.iitb.ac.in/course/view.php?id=13).

## SC/ST Students Cell

The SC/ST students cell addresses difficulties faced by SC/ST students at IIT Bombay.
The activities of the cell are broadly as follows:

- Issues pertaining to SC/ST students' well-being like academic and scholarship matters,
- Awareness and sensitization of IITB community about reservation and caste-related aspects,
- Receive and act on grievances and caste-based-discrimination
  complaints as per prevalent law/procedures.

As a faculty member, you would interact with many students and the institute
maintains a policy of not revealing the birth category of the students to
teachers. It is important to maintain an atmosphere that is inclusive and
conducive to interaction. The students we interact with come from varied
social and economic backgrounds, and students look up to the faculty members
as role-models. Below are some points to keep in mind during your interactions
with students; note that most of the points listed below are applicable to all
students, and not just SC/ST students.

- It is inappropriate to opine negatively about any group of students. It is
  befitting to speak to students solely as individuals and in a calm and
  composed way, without associating him/her to any larger group. Generalised
  phrases like "those people" or "students like you" get perceived as targeted
  at specific groups, and are hence improper.
- A student may have experienced discrimination in the past on the basis of
  caste or other social background, and a seemingly innocuous remark could be
  very hurtful to such a person.
- Communication with casteist undertones is prohibited: whether told casually
  or expressed formally, whether told in official capacity or in personal
  capacity, whether initiated oneself or forwarded/re-posted, orally or in
  print/digital/ social media.
- Faculty members should not make remarks that ridicule the policy of
  reservation; such remarks can be extremely hurtful to those who have availed
  reservation, in addition to potentially violating the code of conduct.
- Some academic options such as exit degrees may be viewed as undesirable by
  students. While it is OK to mention an exit degree as an option, you should be
  sure to list all the other options, and leave the decision
  to the student/parents, without pressurizing them in any way. Recommending it,
  instead of suggesting it as an option, may be done by a committee, not by an
  individual.
- When you tell a student that you will recommend waivers/exemptions, please
  keep in mind that your statement should not sound like a guarantee, and you
  should explain who is the decision making authority.
- In all communication, it is important to have empathy with the student, and
  recognize that the student may have numerous challenges beyond their control,
  and which you are not aware of.

The above guidelines can help to avoid incidents that may make a student feel
discriminated against. However, if any person does feel discriminated against
and files a complaint, the institute must stay neutral and follow due
procedures. The institute takes a strong stand against discrimination of all
forms and will take necessary/appropriate action in both letter and spirit
after an enquiry following standard procedures. With the above points kept in
mind, we are sure that all our student-interactions would be healthy and
fruitful to us faculty-members, the students and the institute.

## Plagiarism
Being an Institute of excellence, the Institute takes a very serious view of any act of plagiarism. While the penal codes are silent on it, there are guidelines issued by National Academies on what constitutes plagiarism. In technical publications, all joint authors are responsible equally for any offence of plagiarism. Punishment can be severe, including termination of service.

## Consultancy ethics
Private consultancy is a serious breach of the code of conduct. Similarly, you should not take up remunerative assignments outside the Institute without explicit permission from the Institute. You should also not accept assignments in a Tutorial organization either as a consultant or for direct teaching.

In case you wish to participate in an external engagement of any kind
(say with another university, industry or any other individual or
organisation), it is mandatory to take permission or obtain a
no-objection from the Dean (FA) to do so. Most reasonable requests are
generally accepted, but breach of procedure is taken seriously by the
Institute.