---
description: "Rules for regularization and confirmation of service for IIT Bombay faculty after the probation period."
keywords: "IIT Bombay regularization, faculty confirmation, probation period, IITB service confirmation"
---

# Regularization/Confirmation of Service {#sec:regularization}

Under the current norms (viz. [7th Pay Commission
rules](https://www.education.gov.in/sites/upload_files/mhrd/files/7th%20CPC%20Order%20CFTIs.pdf),
in particular 1(b)), IITs cannot offer a confirmed faculty position to
one with less than 3 years professional/postdoctoral experience (not
counting any experience gained during the PhD and pre-PhD years). In
such cases, the Institute makes an appointment at the Assistant
Professor Grade-II through its regular selection process. Such
appointees are entitled to all facilities that regular faculty members
may avail. If you are appointed at this level, the administration
keeps track of when you complete the requirement of 3 years of
experience (the experience gained after the date of PhD defence is
counted) and sends a form to you through your academic unit which you
should fill as a part of regularization process. In this form you have
to fill in details of all you academic accomplishments obtained after
your PhD degree and a summary of your academic activities after
joining IIT Bombay. This form is forwarded to Dean (FA) by the Head of
academic unit after adding appropriate recommendations. The Dean (FA)
forwards this to the Director with his/her recommendations. In case
you have prior experience which is declared in the application form
for faculty position, or if you have acquired the experience after
submission of application to the Institute that you feel should be
counted against the 3 years requirement, you may make a representation
through your Head of Department to Dean (FA), along with documentary
evidence of the experience you are claiming.

A faculty member recruited to any cadre is placed on probation for a
period of 1 year. At the end of this period, administration requires
you to fill another form (where you fill in your academic
accomplishments during the probation year) and submit the same to Dean
(FA) through the Head of your academic unit for confirmation of your
appointment. Faculty members are eligible for the Post Retirement
Medical Scheme (PRMS) after confirmation in the service of the
Institute and PRMS is mandatory for every confirmed employee.