# Starting a company based on your research/ technological breakthroughs
The Institute encourages you to capitalize on your research findings
which have an application potential, through starting your own company
or enterprise on campus. This requires that permission be obtained by
applying to the Director, through the Dean (FA)[^imcwork].  The
application process involves, among other things, application of due
diligence to ensure there is no conflict of interest involved. A
company called the [_Society for Innovation and Entrepreneurship
(SINE)_](https://sineiitb.org/)[^sine]  has been created for the sole purpose of facilitating
the transition from laboratory to marketplace by providing incubation
facilities, and is the sole vehicle for translation of
research/technological breakthroughs by the Institute's faculty
members to commercial enterprises. The National Innovation and
Startup Policy also offers incentives to
promote student driven startups and innovations.

[^imcwork]: See link at http://internal.iitb.ac.in/imcwork/faculty/ , also linked from the main IIT Bombay webpage, for details.

[^sine]: Details of the vision and mission, as well as the rules and procedures for incubating a company under SINE are available at http://www.sineiitb.org/