gantt
    todayMarker off
    dateFormat YYYY-MM-DD
    axisFormat %Y
    tickInterval 1year
    section First block
    Home town          :2020-01-01, 2020-12-31
    Home town          :2021-01-01, 2021-12-31
    Home town          :2022-01-01, 2022-12-31
    Anywhere in India  :crit, 2023-01-01, 2023-12-31
    section Second block
    Home town          :2024-01-01, 2024-12-31
    Home town          :2025-01-01, 2025-12-31
    Home town          :2026-01-01, 2026-12-31
    Anywhere in India  :crit, 2027-01-01, 2027-12-31